#+TITLE: Setting up Mediawiki and Moodle for LbD Server
#+AUTHOR: VLEAD Systems
#+DATE: [2017-07-05 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
This document describes about the setting up mediawiki and moodle for LbD server on CentOS-6.9.

** Recommended Hardware requirements for moodle and mediawiki
   - Disk space :: 100GB free (min) plus as much as you need to store
                   your materials. 150GB is probably a realistic
                   minimum.
   - Memory :: 256MB (min), 2GB or more is strongly recommended. The
               general rule of thumb is that Moodle can support 10 to
               20 concurrent users for every 1GB of RAM, but this will
               vary depending on your specific hardware and software
               combination and the type of use. 'Concurrent' really
               means web server processes in memory at the same time
               (i.e. users interacting with the system within a window
               of a few seconds). It does NOT mean people 'logged in'.
                https://docs.moodle.org/23/en/Installing_Moodle#Hardware
** Create Base4 container 
   Create a container on Base4 with the above =recommended hardware requirements= 
   - Create a container on Base4
      #+BEGIN_SRC 
      RAM: 2 GB
      vCPU: 1
      CentOS: 6.9
      DiskSpace: 232 GB
      #+END_SRC

* Install required packages
 - Install *php-5.6*
 #+BEGIN_EXAMPLE
 rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
 rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
 sudo yum install php56w php56w-opcache -y
 sudo yum install php56w-fpm php56w-opcache -y 
 sudo yum install php56w-mysql -y 
 #+END_EXAMPLE
 - Install *mysql-server-5.7.18*
 #+BEGIN_EXAMPLE
 sudo yum install wget -y
 wget https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm
 sudo yum localinstall mysql57-community-release-el6-11.noarch.rpm -y
 sudo yum install -y mysql-community-server
 sudo service mysqld start
 #+END_EXAMPLE
 - Default  or temporary password for root user would be in =/var/log/mysql.log=
 #+BEGIN_EXAMPLE
 sudo grep 'temporary password' /var/log/mysqld.log
 #+END_EXAMPLE

* Install Mediawiki
 Follow the [[https://github.com/vlead/vlabs-learn-by-doing/blob/develop/src/wiki-installation.org][link]] to install mediawiki.

* Install Moodle
 Follow the [[https://github.com/vlead/vlabs-learn-by-doing/blob/develop/src/moodle-installation.org][link]] to install moodle.

* LbD course details of wiki and moodle.
** Source information
 - Balamma, nadeem
** Detailed information of LbD server (production)
 - LbD production server - 10.4.20.76
 - Credentials - Saved in =password.txt= file under systems team 
 - Location of wiki and moodle database in LbD production server.
  + *wikidatabase name:* wiki123db
  + *moodledatabase name:* testmoodle
  + *Credentials:* Saved in =password.txt= file under systems team 
 - Location of wiki, moodle, jmoodledata, lbdvideos and pdf_wiki in LbD production server.
  + *wiki:* =/var/www/html/wiki=
  + *moodle:* =/var/www/html/moodle=
  + *lbdvideos:* =/home/video/lbdvideos=
  + *jmoodledata:* =/var/www/jmoodledata=
  + *pdf_wiki:* =/var/www/html/pdf_wiki=
 - FTP backup server - 10.3.0.63
 - Credentials - Saved in =password.txt= file under systems team 
 - Location of CIT_VIDEOS, MHRDAnimation, animation and animations in ftp server
  + *CIT_VIDEOS:* =/home/CIT_VIDEOS/mhrd/Analog/=
  + *MHRDAnimations:* =/home/databackup/htmlbackup/MHRDAnimations=
  + *animation:* =/home/databackup/htmlbackup/animation=
  + *animations:* =/home/databackup/htmlbackup/animations=
 - Total size of above files is 172GB
** Detailed information of LbD server (local machine in Base4)
 - Local machine - 10.4.12.133
 - Copied wiki and moodle databases from LbD production server to local machine (10.4.12.133)
  + *wiki:* =/root/mysql-dump/=
  + *moodle:* =/root/mysql-dump/=
 - Database details of currently using LbD server in local machine
  + *wikidatabase name:* wikidb
  + *moodledatabase name:* moodledb
 - Copied wiki, moodle, lbdvideos, jmoodledata, pdf_wiki, MHRDAnimations, aninmation, animations and CIT_VIDEOS to local machine
  + *wiki:* =/var/www/html/wiki=
  + *moodle:* =/var/www/html/moodle=
  + *lbdvideos:* =/var/www/html/wiki/lbdvideos=
  + *jmoodledata:* =/var/www/jmoodledata=
  + *pdf_wiki:* =/var/www/html/pdf_wiki=
  + *CIT_VIDEOS:* =/var/www/html/CIT_VIDEOS/mhrd/Analog/=
  + *MHRDAnimations:* =/var/www/html/MHRDAnimations/=
  + *animation:* =/var/www/html/animation/=
  + *animations:* =/var/www/html/animations/=
** Steps to importing files/folders and databases from LbD production server to local machine (Base4:10.4.12.133)
 - Copying wiki and moodle databases from LbD production server to local machine
#+begin_example
rsync -avz -e 'ssh -p 7899' root@10.4.20.76:/root/wiki-13-07-2017.sql /root/mysql-dump/
rsync -avz -e 'ssh -p 7899' root@10.4.20.76:/root/moodle-dump-2017-06-20.sql /root/mysql-dump/
#+end_example
 - Copying wiki, moodle, jmoodledata, pdf_wiki, lbdvideos, MHRDAnimations, animation, animations and CIT_VIDEOS folders from LbD server to local machine (Base4 container) using rsync
#+BEGIN_EXAMPLE
rsync -avz -e 'ssh -p 7899' root@10.4.20.76:/home/backup/wiki/* /var/www/html/wiki/
rsync -avz -e 'ssh -p 7899' root@10.4.20.76:/home/backup/moodle /var/www/html/
rsync -avz -e 'ssh -p 7899' root@10.4.20.76:/var/www/jmoodledata /var/www/
rsync -avz -e 'ssh -p 7899' root@10.4.20.76:/home/video/lbdvideos /var/www/html/wiki/
rsync -avz -e 'ssh -p 7899' root@10.4.20.76:/var/www/html/pdf_wiki /var/www/html/
rsync -avz -e 'ssh -p 7890' root@10.3.0.63:/home/CIT_VIDEOS/mhrd/Analog /var/www/html/
rsync -avz -e 'ssh -p 7890' root@10.3.0.63:/home/databackup/htmlbackup/MHRDAnimations /var/www/html/
rsync -avz -e 'ssh -p 7890' root@10.3.0.63:/home/databackup/htmlbackup/animation /var/www/html/
rsync -avz -e 'ssh -p 7890' root@10.3.0.63:/home/databackup/htmlbackup/animations /var/www/html/
#+END_EXAMPLE
** Chaning domain name from http://enhanceedu.iiit.ac.in to http://lbd.vlabs.ac.in in local machine (Base4)
 - Changing domain name from enhanceedu.iiit.ac.in to lbd.vlabs.ac.in
#+begin_example
grep -rl "enhanceedu.iiit.ac.in" /root/mysql-dump/* |xargs sed -i "s/enhanceedu.iiit.ac.in/lbd.vlabs.ac.in/g"
grep -ri "http://enhanceedu.iiit.ac.in" /var/www/jmoodledata/* |xargs sed -i "s/http:\/\/enhanceedu.iiit.ac.in/http:\/\/lbd.vlabs.ac.in/g"
grep -ri "http://enhanceedu.iiit.ac.in" /var/www/html/* |xargs sed -i "s/http:\/\/enhanceedu.iiit.ac.in/http:\/\/lbd.vlabs.ac.in/g"
#+end_example
** Steps to restore mysql dump in local machine
 - Restoring wiki and moodle databas dump in local machine
#+begin_example
mysql -uroot -pxxxx wikidb < wiki-13-07-2017.sql
mysql -uroot -pxxxx moodledb < moodle-dump-2017-06-20.sql
#+end_example
 - Credentials - Saved in =password.txt= file under systems team
** Access wiki and moodle on browser
 - Click below links on browser
  + [[http://lbd.vlabs.ac.in/moodle/][moodle]]
  + [[http://lbd.vlabs.ac.in/wiki/][wiki]]

* References
1. [[https://download.moodle.org/]]
2. [[https://gitlab.com/vlabs-external-projects/lbd-review-meeting/blob/master/lbd-on-aws.org]]
3. [[https://www.mediawiki.org/wiki/Download]]
4. [[https://webtatic.com/packages/php56/]]
5. [[https://dev.mysql.com/doc/mysql-repo-excerpt/5.6/en/linux-installation-yum-repo.html]]
